In [1]:
import torch

In [25]:
uniform_ps = [0 if batch_points==0 else 1.0 / batch_points for
                       batch_points in [4,67,2,5,7,1,4,76,4,1,0]]

In [32]:
batch_mask = torch.nonzero(torch.tensor([0 if i == 0 else i for i in uniform_ps]))
batch_mask

tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [37]:
gt_dens=gt_dens[batch_mask]
gt_dens=gt_dens.reshape(gt_dens.shape[0],gt_dens.shape[2])
gt_dens

tensor([[1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        ...,
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.]])

In [36]:
gt_dens = torch.ones((len(uniform_ps),1024))

In [38]:
for i, term in enumerate(uniform_ps):
    gt_dens[i]*=term

IndexError: index 10 is out of bounds for dimension 0 with size 10

In [35]:
gt_dens.shape

torch.Size([10, 1, 1024])

In [10]:
torch.zeros(5,1024)

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [ ]:
import torch
x_cood = torch.arange(0, 256, step=8,
                                   dtype=torch.float32) + 4
y_cood = torch.arange(0, 256, step=8,
                            dtype=torch.float32) + 4
X, Y = torch.meshgrid(x_cood, y_cood)
cood_space = torch.dstack((X, Y))
cood_space = cood_space.reshape((cood_space.shape[0]*cood_space.shape[1],
                                            cood_space.shape[2]))